cms/urls.py
from django.urls import path
from .views import *



app_name = 'cms'

urlpatterns = [   
    path('latest/blogs/', latest_blogs, name='latest_blogs'),       
    path('category/<str:slug>', category_detail, name='category_detail'),    
    path('archive/<int:year>/<int:month>', archive_detail, name='archive_detail'), 
    path('<str:username>/blogs/', user_blogs, name='user_blogs'), 
  
    
]

main/urls.py
from django.urls import path
from .views import *
from .sitemaps import *
from cms.views import (
    page_detail, 
    blog_detail

)
from selfurl.views import redirect_url
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView

app_name = 'main' 

sitemap_list = {
    'static': StaticSitemap,
    'pages' : PageSitemap,
    'category' : CategorySitemap,
    'BlogSitemap' : BlogSitemap,
    'UserBlogSitemap':UserBlogSitemap,
    'BlogArchiveSitemap' : BlogArchiveSitemap,
    'UrlVersionsSitemap' : UrlVersionsSitemap,
    'VisiorLogPdfSitemap' : VisiorLogPdfSitemap,
    'ClickedPdfSitemap' : ClickedPdfSitemap
}

urlpatterns = [
    path('', index, name='home'),  
    path('b/<str:slug>/', blog_detail, name='blog_details'),    
    path('p/<str:slug>/', page_detail, name='page_detail'), 
    path('webmanifest/', webmanifest, name='webmanifest'),     
    path('sitemap.xml', sitemap, {'sitemaps': sitemap_list}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    path('<str:short_url>', redirect_url, name='redirect_url'),           
     
    
]

selfurl/urls.py
from django.urls import path
from .views import *
from django.views.generic.base import TemplateView



app_name = 'selfurl'



urlpatterns = [ 
    path('report-malicious/', report_malicious, name='report_malicious'),
    path('statistics/', statistics, name='statistics'),   
    path('makeshort/', makeshort, name='makeshort'),   
    path('versions/<str:short_url>', versions, name='versions'),   
    path('create-version/<str:short_url>', create_version, name='create_version'),  
    path('logs/<str:short_url>/', log_details, name='log_details'), 
    path('set-expire/<int:id>/', set_expire, name='set_expire'), 
    path('malicious-submit/', malicious_submit, name='malicious_submit'), 
    path('allreport/<str:short_url>', allreport, name='allreport'),
    path('report-pdf/<str:short_url>', generate_visitor_log_pdf, name='generate_visitor_log_pdf'),
    path('click-record-pdf/<str:short_url>', generate_click_record_pdf_view, name='generate_click_record_pdf_view'),
    
    
] 

selfurl/forms.py
from django import forms
from .models import Shortener, Versions
from captcha.fields import ReCaptchaField
from captcha.widgets import ReCaptchaV2Invisible, ReCaptchaV2Checkbox
from django.db.models import Q
from accounts.forms import DateInput

class SetExpireDateForm(forms.ModelForm):
    
    class Meta:
        model = Shortener
        fields = ('expires_at',)
        
        widgets = {                      
            'expires_at': DateInput(attrs={'data-datepicker': "" , 'class':'form-control', 'aria-label':'birthdate', }),              
        }


class CreateVersionForm(forms.ModelForm):
    
    class Meta:
        model = Versions
        fields = ('version',)
        
        widgets = {                      
            'version': forms.TextInput(attrs={'placeholder': 'Write new version', 'class':'form-control', 'aria-label':'Version'}),                
        }
        
    def clean_version(self):
        version = self.cleaned_data['version']
        # Combine the filter conditions using Q objects
        existing_versions = Q(version=version)
        existing_short_urls = Q(short_url__iexact=version)

        # Check if the submitted version already exists in urlversion
        if Versions.objects.filter(existing_versions).exists():
            raise forms.ValidationError('This version already exists in urlversion.')

        # Check if the submitted version matches the slug field in Shortener
        if Shortener.objects.filter(existing_short_urls).exists():
            raise forms.ValidationError('The version already exists in the database.')


        return version
    

class ShortenerForm(forms.ModelForm):    
    long_url = forms.URLField(widget=forms.URLInput(
        attrs={"class": "form-control", "placeholder": "Your URL to shorten"}))
  
    
    
    class Meta:
        model = Shortener
        fields = ('long_url',)
        
class CheckingForm(forms.Form):   
    from django.contrib.sites.models import Site
    
    short_url = forms.CharField(
        max_length=15, 
        widget=forms.TextInput(
        attrs={"class": "form-control rounded-0", 'placeholder': "Enter last part of url" }),
        label=Site.objects.get_current().domain + '/'
        )
    reasons = forms.CharField(
        label='Reasons you are reporting for',  # The label for the text field
        widget=forms.Textarea(attrs={'rows': 4, 'placeholder': 'Reasons you are reporting for', 'class': 'form-control'}),  # Textarea widget with 4 rows
        max_length=500,  # Optionally, you can set the maximum length of the text
        required=True,  # Set to True if the field is required
        help_text="This report is requested to be done honestly. Because with this report, the target URL will be closed for all those who have taken our service to shorten it for their needs. Your dishonesty may cause us to lose business."
        
    )
    captcha = ReCaptchaField( widget=ReCaptchaV2Checkbox)  
    

selfurl/views.py
import base64
import random
import string
from django.conf import settings
from django.utils import timezone
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import login_required
from main.context_processor import site_info
from django.contrib import messages
from django.views.decorators.cache import cache_control
from main.helper import check_exists, is_reported
from main.tasks import send_mass_mail_task
from .forms import (
    CheckingForm, 
    ShortenerForm, 
    CreateVersionForm, 
    SetExpireDateForm
)
from .models import (
    Shortener,
    VisiLogSecretKey, 
    VisitorLog, 
    ReportMalicious,
    Versions
)
from main.agent_helper import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import arrow
from cryptography.fernet import Fernet
from django.db.models import Count, Q
from django.core.mail import send_mass_mail

import io
import matplotlib.pyplot as plt
import matplotlib
from reportlab.lib.pagesizes import letter, A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Table, TableStyle, KeepTogether, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.graphics.shapes import Drawing, String, Circle, Line
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER

from django.core.exceptions import PermissionDenied

 
    
    
def redirect_url(request, brand=None, short_url = None): 
    if request.user_agent.is_bot:
        return HttpResponse('Request not accepted! Please contact US!')   
    
    found = '' 
    
    try:
        # Query the Shortener model
        shortener = Shortener.objects.get(short_url=short_url, active=True)
        found = 'main_short'
    except Shortener.DoesNotExist:
        try:
            # Query the Versions model
            version = Versions.objects.get(version=short_url)
            shortener = version.url
            found = 'version_short'
        except Versions.DoesNotExist:
            raise Http404('Not Found!')
        
    # if url reported as malicious it will not redirect
    if is_reported(shortener.long_url):
        shortener.active = False
        shortener.save()
        raise Http404('The Redirector is inactive')
    
    #if expires_at none it means it will not expire anymore
    if not shortener.expires_at:
        shortener.active = True
        shortener.save()
    else:
        # expires_at less then current date it will not redirect and make inactive here.
        # So will do not need to run cronjob
        if shortener.expires_at < timezone.now():        
            shortener.active = False
            shortener.save()
            raise Http404('The Redirector is inactive')       

    
    shortener.clicked += 1
    shortener.save()
    
    if found == 'version_short':
        version.clicked += 1
        version.save()
        
        
    # Generate a random secret key for the user
    user_secret_key = Fernet.generate_key()

    # Create a Fernet cipher suite using the user secret key
    cipher_suite = Fernet(user_secret_key)    
    
    user_agent = get_agent(request)   
    # Convert the user_agent dictionary to a JSON string
    user_agent_json = json.dumps(user_agent)
    # print(user_agent_json)
    # Encrypt the user_agent dict
    encrypted_user_agent = cipher_suite.encrypt(user_agent_json.encode())    
    
    geodata = get_geodata(request)    
    # Convert the geodata dictionary to a JSON string
    geodata_json = json.dumps(geodata)
    # print(geodata_json)
    # Encrypt the geodata dict
    encrypted_geodata = cipher_suite.encrypt(geodata_json.encode())  
    
    encoded_key = base64.b64encode(user_secret_key)      
        
    visitor_log = VisitorLog.objects.create(
        shortener=shortener,           
        user_agent = encrypted_user_agent, 
        geo_data = encrypted_geodata,        
    )  
    # Create a VisiLogSecretKey object and associate it with the VisitorLog instance
    VisiLogSecretKey.objects.create(v_log=visitor_log, key=encoded_key)         
    
    redirect_to = shortener.long_url   
    
    return HttpResponseRedirect(redirect_to)   

@login_required
@cache_control(no_cache=True, must_revalidate=True, no_store=True)   
def log_details(request, short_url):  
    if request.user.is_paid or request.user.is_superuser:
        pass
    else:
        raise PermissionDenied
    
    shortener = Shortener.objects.prefetch_related('visitorlogs__logkey', 'reporturl').get(short_url = short_url)
    if is_reported(shortener.long_url):
        raise Http404
    visit_logs = shortener.visitorlogs.all()
    for vl in visit_logs:
        secret_key = base64.b64decode(vl.logkey.key)
        cipher_suite = Fernet(secret_key)        
        decrypted_user_agent = json.loads(cipher_suite.decrypt(vl.user_agent))
        decrypted_geodata = json.loads(cipher_suite.decrypt(vl.geo_data))    
        
        vl.ip = decrypted_geodata.get('IPv4')
        vl.country = decrypted_geodata.get('country_name')
        vl.city = decrypted_geodata.get('city')
        vl.postal = decrypted_geodata.get('postal')
        vl.state = decrypted_geodata.get('state') 
        vl.lat = decrypted_geodata.get('latitude')
        vl.long = decrypted_geodata.get('longitude')
        vl.user_usage = decrypted_user_agent.get('user_usage')
        vl.user_browser = str(decrypted_user_agent.get('user_browser')[0]) +'-'+ str(decrypted_user_agent.get('user_browser')[2])
        vl.user_os = str(decrypted_user_agent.get('user_os')[0]) +'-'+ str(decrypted_user_agent.get('user_os')[2])
        vl.user_device = str(decrypted_user_agent.get('user_device')[0]) +'-'+ str(decrypted_user_agent.get('user_device')[2])    

        
    #Paginated response
    page = request.GET.get('page', 1)
    paginator = Paginator(visit_logs, 10)
    try:
        visit_logs = paginator.page(page)
    except PageNotAnInteger:
        visit_logs = paginator.page(1)
    except EmptyPage:
        visit_logs = paginator.page(paginator.num_pages)
        
    # Every time someone clicks on your short URL, our technology will keep track. It doesn't matter if it came from the same device or from the same person.
    # Visitor Logs of shorten URL-
    
    context = {             
        'site_data' : site_info(),                  
        'visit_logs' : visit_logs,
        'short_url' : short_url,
        'reports':  shortener.reporturl.all()[:10],
        'clicked':  shortener.clicked          
            }
    response =  render(request, 'selfurl/log_details.html', context = context)
    response['X-Robots-Tag'] = 'noindex, nofollow'
    return response

    
    
@login_required
def set_expire(request, id):
    """
    This function sets the expiration date for a shortened URL.

    Args:
        request (django.http.HttpRequest): The HTTP request object.
        id (int): The ID of the shortened URL.

    Returns:
        django.http.HttpResponse: The HTTP response object.
    """
    template = "selfurl/set_expire.html"
    form = SetExpireDateForm()
    item = Shortener.objects.get(id =id)
   
    # If the request method is POST, then process the form data.
    
    if request.method == 'POST':
        form = SetExpireDateForm(request.POST)
        if form.is_valid(): 
            expires_at = form.cleaned_data["expires_at"]  
            
            # Set post data as expire data
               
            item.expires_at = expires_at
            
            # If the expiration date is in the future or is not set,
            # and the shortened URL is not reported as malicious,
            # then set the shortened URL to active.
            
            if (not expires_at or expires_at > timezone.now() ) and not is_reported(item.long_url):
                item.active = True
            else:
                item.active = False
             
            # Update Item   
            item.save()
        else:
            messages.error(request, 'Invalid form submission.')
            messages.error(request, form.errors)  
        
        # Get the updated shortened URL object.
        
        item.refresh_from_db()  
 
        # We will not pass get form in post request
        # to control template code as it is requesting by HTMX.
        # And we will return for post request
        
        context = {            
            'item' : item            
        }        
        response = render(request, template, context = context) 
    
        response['X-Robots-Tag'] = 'noindex, nofollow'
        return response
    
    # As the function is calling by HTMX will will return 
    # form and item both fot get request
    # it suports template code control.
            
    context = {
        'form' : form,
        'item' : item        
    }    
    return render(request, template, context = context)

def get_data_versions(request, short_url):
    data = get_object_or_404(Shortener.objects.prefetch_related('urlversion'), short_url=short_url)
    if is_reported(data.long_url):
        raise Http404
    versions = data.urlversion.all()
    
    page = request.GET.get('page', 1)
    paginator = Paginator(versions, 10)
    try:
        versions = paginator.page(page)
    except PageNotAnInteger:
        versions = paginator.page(1)
    except EmptyPage:
        versions = paginator.page(paginator.num_pages)   
        
    return data, versions

@login_required    
def create_version(request, short_url):
    template = 'selfurl/create_versions.html'    
    form = CreateVersionForm()
   
    data, versions = get_data_versions(request, short_url)
    
    if is_reported(data.long_url):
        raise Http404
        
    if request.method == 'POST':
        form = CreateVersionForm(request.POST)
        if form.is_valid():   

templates/selfurl/create_versions.html
{% load static %}
<div class="col-lg-8 text-start align-center">
    {% if messages %}                                                     
        {% for message in messages %}
        <em class="text-danger ">{{ message }}</em> 
        {% endfor %} 
    {% else %} 
    {% endif %} 
</div>  

{% if form %}
<form class="alert alert-info" hx-post="{% url 'selfurl:create_version' data.short_url %}" hx-target="#version_area" hx-swap="innerHTML">
    {% csrf_token %}
    <div class="input-group">
        <span class="input-group-text">{{site_data.domain}}/</span>
        {{ form.version }}
        <input type="submit" class="btn btn-primary" value="Create"/>
    </div>
    <span class="text-error invalid-feedback">{{ form.errors }}</span>
</form>
<div class="row justify-content-center g-4">
<h4 class="custom-underline text-center fs-2">Craft a New Version of Your URL</h4>
<p class="text-center">
    Enhance your link's appeal and share it uniquely by simply entering the desired URL path after our domain in the box above. 
    Instantly create a fresh version that stands out! To ensure uniqueness, we'll notify you if the version already exists, 
    prompting you to select an alternative. Click the 'Create' button to bring your custom version to life and start sharing it with the world!<span class="end-icon"></span>
</p>
</div>


{% else %}
    {% if versions %} 
        <div class="row">
            <div class="col">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Version</th>
                            <th>Clicked</th>
                            <th>Created</th>
                        </tr>
                    </thead>
                    <tbody >
                        {% include 'selfurl/versions_table_body.html' %} 
                    </tbody>
                </table>
            </div>
        </div>          
        <a class="btn btn-primary" hx-get="{% url 'selfurl:create_version' data.short_url %}" hx-target="#version_area" hx-swap="innerHTML">Add More</a>  
        
    {% else %}           
            <p class="alert alert-info">No Version Found!<a class="btn btn-primary" hx-get="{% url 'selfurl:create_version' data.short_url %}" hx-target="#version_area" hx-swap="innerHTML">Click Here</a> to create one!</p>

    {% endif %}
{% endif %}

templates/selfurl/makeshort.html
{% load static %}

<div id="indicator" class="htmx-indicator"><i class="fa-solid fa-arrows-rotate text-success fa-3x fa-spin-pulse"></i></div>

{% if data %}
    <div class="row g-3 align-items-center justify-content-center">
        <div class="col-lg-10 alert alert-primary">
            <h2 class="text-danger">Your Shortened URL</h2>
            <div class="d-flex justify-content-center align-items-center">
                <div class="col-auto me-2">
                    <input id="urlresult" class="form-control" type="text"
                        value="{{site_data.domain}}/{{data.short_url}}">
                </div>
                
            </div>
            <p class="mt-3">Share your link with ease! Just click the <span><button onclick="copy()" class="btn btn-sm btn-primary">Copy</button> </span>
                button to grab the link and share it with your audience.</p><p class="mt-3"> Need more versions?
                 No problem! Explore <span><a href="{% url 'selfurl:versions' data.short_url %}" class="btn btn-sm btn-warning">More Versions</a></span> to create limitless customized URLs. 
                 Follow the instructions on the redirected page after clicking <span><a href="{% url 'selfurl:versions' data.short_url %}" >More Versions</a></span> to get started.</p>     
    


            <div class="row g-3 align-items-center">
                <p><span class="text-danger">The short URL created from:</span> {{data.long_url}}</p>
            </div> 
        </div>
    </div>


    <script type="text/javascript">
        function copy() {
            let textarea = document.getElementById("urlresult");
            textarea.select();
            document.execCommand("copy");
        }
       
    </script>
{% else %}
    <div class="col-lg-6">
        <form hx-post="{% url 'selfurl:makeshort' %}" hx-target="#url_response" hx-swap="innerHTML" hx-indicator="#indicator">
            {% csrf_token %}
            <div class="input-group mb-3 mt-3">
                {{ form.long_url }}
                <input type="submit" class="btn btn-danger" value="Make Short"/>
            </div>
            <span class="text-error invalid-feedback">{{ form.long_url.errors }}</span>
        </form>
        
    </div>
    {# {% include "layouts/ads_display.html" %} #}
{% endif %}
<div class="col-lg-12 text-start align-center">
    {% if messages %}                                                     
        {% for message in messages %}
        <em class="text-danger ">{{ message }}</em> 
        {% endfor %} 
    {% else %} 
    {% endif %} 
</div> 

templates/selfurl/malicious_submit.html
{% load static %}
<div  class="col-auto text-center align-items-center justify-content-center">   
    <form hx-post="{% url 'selfurl:malicious_submit' %}" hx-target="#malicious_respose" hx-swap="innerHTML" hx-indicator="#indicator">
        {% csrf_token %}                    
        <div class="col mt-3 justify-content-center align-items-center">  
            <div class="d-flex justify-content-center align-items-center mb-2">  
            {{ form.captcha }}
            </div>
            <div class="d-flex form-group">                            
                <input type="text" class="form-control text-end rounded-0 rounded-start" value="{{form.short_url.label}}"  disabled>      
                {{ form.short_url }}                              
            </div> 
            <div class="form-group">      
                {{ form.reasons }}  
                <small class="text-danger">**{{ form.reasons.help_text }}</small>   
            </div>   
            <input type="submit" class="btn btn-primary" value="Submit"/>       
            <span><img id="indicator" class="htmx-indicator" src="{% static 'loading.gif' %}"  width="80" height="80"></span>

        </div>
        <span class="text-error invalid-feedback">{{ form.long_url.errors }}</span>                            
    </form>
</div>    
<div class="col-lg-12 text-start align-center">
    {% if messages %}                                                     
        {% for message in messages %}
        <em class="text-danger ">{{ message }}</em> 
        {% endfor %} 
    {% else %} 
    {% endif %} 
</div>    
<div class="mt-2">
    {# {% include "layouts/ads_boom_your_identity.html" %} #}
</div>

templates/selfurl/set_expire.html
{% load selfurl_tags %}
{% if form %}
    <form hx-post="{% url 'selfurl:set_expire' item.id %}" hx-target="#expire_area{{item.id}}" hx-swap="innerHTML">
        {% csrf_token %}
        <div class="position-relative mt-3">
            <div class="input-group mb-3">
            {{ form.expires_at }}
            <input type="submit" class="btn btn-primary" value="Set"/>        
            </div>
        </div>
        <span class="text-error invalid-feedback">{{ form.expires_at.errors }}</span>
    </form>

    <div class="col-lg-8 text-start align-center">
        {% if messages %}                                                     
            {% for message in messages %}
            <em class="text-danger ">{{ message }}</em> 
            {% endfor %} 
        {% else %} 
        {% endif %} 
    </div> 
{% else %}
    <a data-bs-toggle="tooltip" data-bs-placement="top" title="Will not work after selected date! mm/dd/yyyy will set for infinity." class="text-primary mb-0" href="" hx-get="{% url 'selfurl:set_expire' item.id %}" hx-target="#expire_area{{item.id}}" hx-swap="innerHTML">
        <b>Expires at</b> 
        {% if item.expires_at == none %}Infinity{% else %}{{item.expires_at}}{% endif %}*
    </a><br>    
    <small>* Click on the Expire at. URL will not accessible after selected date! mm/dd/yyyy never expire.</small>
    <div class="d-flex justify-content-between align-items-center border-top border-bottom py-2">
        <div class=" mb-0 {% if item.active == True  %}  text-success {% else %} text-danger {% endif %} ">
        Active__{{item.active}}**         
        {% if item.long_url|is_reported  %}   
        || 
        <span class="text-danger"><b>Reported***</b></span><br> 
        <small>*** we have {{ item.long_url|report_que }} que to check reported URL and we need atleast 5 min to 24 hrs to check each reported URL. IF check found that it is reported wrong then will be activated if expire date demand</small>
        {% endif %}
        </div>          
    </div>
    <small>** Active True or False Changed based on the expire date and by checking is it reported as melicious or not.</small>
{% endif %}

templates/selfurl/statistics.html
{% extends "layouts/base.html" %}
{% load static %}
{% load selfurl_tags %}
 
{% block robot %}<meta name="robots" content="noindex">{% endblock %}


{% block content %}

<div class="d-flex align-items-center p-3 my-3 text-primary bg-warning rounded shadow-sm">
    <img class="me-3" src="{{  site_data.og_image }}" alt="{{request.user.username}}" width="48" height="48">
    <div class="lh-1">
        <h1 class="h6 mb-0 text-primary lh-1">Shortened URL</h1>
        <small>Since {{created_since}}</small>
    </div>
</div>

<div class="row justify-content-center">
    <div class="col-lg-6 text-start align-center">
        {% if messages %}
        {% for message in messages %}
        <em class="text-danger ">{{ message }}</em>
        {% endfor %}
        {% else %}
        {% endif %}
    </div>
</div>


<div class="my-3 p-3 bg-body card">
    <div class="text-center align-items-center justify-content-center border-bottom">
        <h1 class="text-danger ">{{site_data.title}}</h1>

        <p class="text-primary ">{{site_data.description}}</p>
        {# {% include "layouts/ads_display.html" %} #}
    </div>
    <div class="row d-flex align-items-center justify-content-center">
        <div class="col-lg-12">
            <div class="mt-2">
                {# {% include "layouts/ads_boom_your_identity.html" %} #}
            </div>
            {% for item in items %}
            <div class="text-muted p-3 mb-3 border border-2 border-secondary rounded-3 bg-light bg-gradient">
                <p class="bg-secondary p-3 text-white text-center rounded rounded-3">
                    {{item.clicked}} <br> <small>Clicks</small>
                </p>
                <div
                    class="pb-0 mb-0 small lh-sm border-bottom align-items-center justify-content-center d-block my-auto">
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="col-lg-6 p-2">
                            <strong class="d-block text-gray-dark">
                                <a class="text-primary mb-0" href="/{{item.short_url}}"
                                    target="_blank">{{site_data.domain}}/{{item.short_url}}</a>
                            </strong>
                            <div class="py-2">
                                Created On__{{item.created}}                        
                            </div>
                        </div>
                        <div class="col-lg-6 p-2" id="expire_area{{item.id}}">
                            {% include 'selfurl/set_expire.html' with item=item %}
                        </div>
                    </div>
                    
                    <div class="card-footer text-strat ps-0">
                        {{item.long_url}}
                    </div>
                    <div class="justify-content-end align-items-end text-end mt-2 mb-1">
                        {% if request.user.is_paid or request.user.is_superuser %}
                        <a class="badge btn-danger" href="{% url 'selfurl:log_details' item.short_url  %}">Visitor's Logs </a>
                        {% endif %}
                        {% if not item.long_url|is_reported %}
                        <a class="badge btn-success" target="_blank" href="{% url 'selfurl:generate_visitor_log_pdf' item.short_url  %}">Analytic PDF</a>
                        <a class="badge btn-success" target="_blank" href="{% url 'selfurl:generate_click_record_pdf_view' item.short_url %}">Clicked PDF</a>

                        <a class="badge btn-primary" href="{% url 'selfurl:versions' item.short_url  %}">Versions </a>
                        {% endif %}

                    </div>
                </div>
            </div>
            {# {% include "layouts/ads_infeed.html" %} #}
            {% endfor %}
        </div>
        <div class="col-lg-6">
            {# {% include "layouts/ads_multiplex.html" %} #}
        </div>
    </div>

    <div class="d-flex align-items-end justify-content-end">
        <small class="d-block text-end mt-3 ">
            <div class=" border-0 d-flex flex-column flex-lg-row align-items-center justify-content-between">
                <nav aria-label="Page navigation ">
                    <ul class="pagination justify-content-center">
                        {% if items.has_previous %}
                        <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a>
                        </li>
                        <li class="page-item"><a class="page-link"
                                href="?page={{ items.previous_page_number }}">previous</a></li>
                        {% endif %}

                        <li class="page-item page-link"> Page {{ items.number }} of {{items.paginator.num_pages }}.
                        </li>

                        {% if items.has_next %}
                        <li class="page-item"><a class="page-link" href="?page={{ items.next_page_number }}">next</a>
                        </li>
                        <li class="page-item"> <a class="page-link" href="?page={{ items.paginator.num_pages }}">last
                                &raquo;</a></li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        </small>
    </div>
    {# {% include "layouts/ads_display.html" %} #}
</div>

{% endblock %}

templates/selfurl/versions_table_body.html
{% load static %}

    {% for version in versions %}                        
    <tr>                            
        <td><a href="{% url 'main:redirect_url' version.version %}">{{site_data.domain}}/{{version.version}}</a></td>
        <td>{{version.clicked}}</td>
        <td>{{version.created}}</td>                             
    </tr>  
    {% endfor %}    
    {% if versions.has_next %}                                               
        <tr id="replaceMe">
            <td colspan="3" class="text-center">
            <button class='btn btn-outline-primary' 
                hx-get="{% url 'selfurl:create_version' data.short_url %}?page={{ versions.next_page_number }}"
                hx-target = "#replaceMe"
                hx-trigger="click"
                hx-swap="outerHTML"
                hx-vals='{"getpage": "getpage"}'>
                Load More... 
            </button>
            <img class="htmx-indicator" src="{% static 'loading.gif' %}">
            </td>
        </tr>  
      {% endif %}              