cms/urls.py
from django.urls import path
from .views import *



app_name = 'cms'

urlpatterns = [   
    path('latest/blogs/', latest_blogs, name='latest_blogs'),       
    path('category/<str:slug>', category_detail, name='category_detail'),    
    path('archive/<int:year>/<int:month>', archive_detail, name='archive_detail'), 
    path('<str:username>/blogs/', user_blogs, name='user_blogs'), 
  
    
]

main/urls.py
from django.urls import path
from .views import *
from .sitemaps import *
from cms.views import (
    page_detail, 
    blog_detail

)
from selfurl.views import redirect_url
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView

app_name = 'main' 

sitemap_list = {
    'static': StaticSitemap,
    'pages' : PageSitemap,
    'category' : CategorySitemap,
    'BlogSitemap' : BlogSitemap,
    'UserBlogSitemap':UserBlogSitemap,
    'BlogArchiveSitemap' : BlogArchiveSitemap,
    'UrlVersionsSitemap' : UrlVersionsSitemap,
    'VisiorLogPdfSitemap' : VisiorLogPdfSitemap,
    'ClickedPdfSitemap' : ClickedPdfSitemap
}

urlpatterns = [
    path('', index, name='home'),  
    path('b/<str:slug>/', blog_detail, name='blog_details'),    
    path('p/<str:slug>/', page_detail, name='page_detail'), 
    path('webmanifest/', webmanifest, name='webmanifest'),     
    path('sitemap.xml', sitemap, {'sitemaps': sitemap_list}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    path('<str:short_url>', redirect_url, name='redirect_url'),           
     
    
]

templates/includes/meta.html
{% load static %}

<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="msvalidate.01" content="C960B076480CA5EDEB68F2B60FA3A8B6" />
<meta name="google-site-verification" content="MGTtBLWPpiQbR7H6gZEfcLmjDP0bsmFP3Aa7U8iRmjE" />
<meta name="facebook-domain-verification" content="msn2jr9554t197xn4dw93k9p2v46qh" />
<meta name="propeller" content="70a6f1647519f6eebf337a10389233e4">
<meta name="ahrefs-site-verification" content="65fb77a34efdf9d9daa566a15ed50ebad3f212b2866a6681205e40800a086477">



<title>{{ site_data.name }} -{{ site_data.title }}</title> 
<meta name="description" content="{{ site_data.description }}">
<meta name="author" content="{{ site_data.author }}">
<meta property="og:title" content="{{ site_data.name }} - {{ site_data.title }}">
<meta property="twitter:title" content="{{ site_data.name }} - {{ site_data.title }}">
<meta property="og:description" content="{{ site_data.description }}">
<meta property="twitter:description" content="{{ site_data.description }}">
<meta property="og:type" content="website">
<meta property="twitter:card" content="summary_large_image">
<meta property="og:image" content="{{request.scheme}}://{{site_data.domain}}{{ site_data.og_image }}">
<meta property="twitter:image" content="{{request.scheme}}://{{site_data.domain}}{{ site_data.og_image }}">
<meta property="og:url" content="{{ request.build_absolute_uri }}">
<link rel="canonical" href="{{ request.build_absolute_uri }}">
<meta property="twitter:url" content="{{ request.build_absolute_uri }}">
<meta name="twitter:site" content="@selfurlxyz" />
<meta name="twitter:creator" content="@selfurlxyz" /> 
<meta name="category" content="company"/>

<!-- Favicon -->
<link rel="apple-touch-icon" sizes="120x120" href="{{request.scheme}}://{{site_data.domain}}{{ site_data.favicon }}">
<link rel="icon" type="image/png" sizes="32x32" href="{{request.scheme}}://{{site_data.domain}}{{ site_data.favicon }}">
<link rel="icon" type="image/png" sizes="16x16" href="{{request.scheme}}://{{site_data.domain}}{{ site_data.favicon }}">
<link rel="manifest" href="{% url 'main:webmanifest' %}">
<link rel="mask-icon" href="{{request.scheme}}://{{site_data.domain}}{{ site_data.mask_icon }}" color="#ffffff">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="theme-color" content="#ffffff">

templates/includes/pagination.html
<div class=" border-0 d-flex flex-column flex-lg-row align-items-center justify-content-between">
    <nav aria-label="Page navigation ">
        <ul class="pagination justify-content-center">
            {% if page.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1">&laquo; first</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page.previous_page_number }}">previous</a>
            </li>
            {% endif %}

            <li class="page-item page-link"> Page {{ page.number }} of {{ page.paginator.num_pages }}.
            </li>

            {% if page.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page.next_page_number }}">next</a></li>
            <li class="page-item"> <a class="page-link" href="?page={{ page.paginator.num_pages }}">last
                    &raquo;</a></li>
            {% endif %}
        </ul>
    </nav>
</div>

templates/includes/scripts.html
{% load static %}

<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>  
<script src="{% static 'vendor/aos/aos.js' %}"></script>
<script>AOS.init();</script>


<script nonce="{{ CSP_NONCE }}" type="application/javascript">
    document.body.addEventListener('htmx:configRequest', (e) => {
        e.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
        })
</script>