cms/urls.py
from django.urls import path
from .views import *



app_name = 'cms'

urlpatterns = [   
    path('latest/blogs/', latest_blogs, name='latest_blogs'),       
    path('category/<str:slug>', category_detail, name='category_detail'),    
    path('archive/<int:year>/<int:month>', archive_detail, name='archive_detail'), 
    path('<str:username>/blogs/', user_blogs, name='user_blogs'), 
  
    
]

contact/urls.py
from django.urls import path
from . views import *



app_name = 'contact'

urlpatterns = [
    path('', contact, name='contact'),
    path('threads/<str:email>', threads, name='threads'), 
    path('threads-reply-form/<int:id>', get_reply_form, name='get_reply_form'), 
    path('post-reply/<int:id>', post_reply, name='post_reply'),    
       
       
        
    
]

contact/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.utils.translation import activate, gettext_lazy as _

# Create your models here.
class ContactMessage(models.Model):
    STATUS_CHOICES = (
        ('active', _('Active')),
        ('closed', _('Closed')),
              
    )    
    name = models.CharField(max_length=255)
    phone_number = PhoneNumberField()
    email = models.EmailField()
    subject = models.CharField(max_length=251)  
    message = models.TextField()
    status = models.CharField(choices=STATUS_CHOICES, max_length=20, default='active')
    
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.name} ({self.email})'
    
    
class Reply(models.Model):      
    thread = models.ForeignKey(ContactMessage, on_delete=models.CASCADE, related_name ='threads')   
    message = models.TextField()
    reply_email = models.EmailField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    

    def __str__(self):
        return f'{self.message}'

contact/forms.py
from django import forms
from .models import ContactMessage, Reply
from phonenumber_field.formfields import PhoneNumberField
from phonenumber_field.widgets import PhoneNumberPrefixWidget, RegionalPhoneNumberWidget, PhonePrefixSelect
from captcha.widgets import ReCaptchaV2Invisible, ReCaptchaV2Checkbox
from captcha.fields import ReCaptchaField


class ThreadReplyForm(forms.ModelForm):
    captcha = ReCaptchaField(widget=ReCaptchaV2Checkbox, label='')  
    class Meta:
        model = Reply
        fields = ['message']
        
        widgets = {
            'message': forms.Textarea(attrs={'rows':'3','placeholder': 'Message', 'aria-label':'message', 'class': 'form-control' }), 
        }
        labels = {
            'message' : '',
            'captcha' : ''
        }


class ContactUsForm(forms.ModelForm):    
    captcha = ReCaptchaField( widget=ReCaptchaV2Checkbox)  
    class Meta:
        model = ContactMessage
        fields = ['name', 'phone_number', 'email', 'subject', 'message']        
        
        widgets = {                      
            'name': forms.TextInput(attrs={'placeholder': 'Name', 'aria-label':'Name', 'class': 'form-control'  }),  
            'phone_number' : PhoneNumberPrefixWidget(initial='GB', attrs={'placeholder': 'Enter phone number', 'aria-label':'phone_number'}, number_attrs ={'class':'form-control'} , country_attrs={'class': 'input-group-text'}) ,
            'email': forms.EmailInput(attrs={'placeholder': 'email',  'aria-label':'email' , 'class': 'form-control' }),                
            'subject': forms.TextInput(attrs={'placeholder': 'Subject',  'aria-label':'subject', 'class': 'form-control'  }),            
            'message': forms.Textarea(attrs={'rows':'5','placeholder': 'Message', 'aria-label':'message', 'class': 'form-control' }), 
        }
        
        PhoneNumberPrefixWidget(attrs={'placeholder': 'Enter phone number'})

contact/views.py
from django.http import Http404, HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse, reverse_lazy
from .forms import *
from django.contrib import messages
from django.conf import settings
from main.context_processor import site_info
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from main.templatetags.selfurl_tags import base64_encode, base64_decode
from main.helper import (
 
    custom_send_mass_mail,
    has_threads, 
    
    )
@login_required
def post_reply(request, id):
    template_name = 'contact/post_reply.html'

    if request.method == 'POST':
        thread = ContactMessage.objects.get(id = id)
        form = ThreadReplyForm(request.POST)
        if form.is_valid():
            message = form.cleaned_data['message']
            Reply.objects.create(thread = thread, message = message, reply_email=request.user.email  )
            reply_instruction = request.POST.get('status')

            if reply_instruction:
                thread.status = 'close'
                thread.save()    
            context = {
                'reply' : message,                   
            }
            return render(request, template_name, context=context)            
        else:
            messages.error(request, 'There was an error with your submission. Please try again.')
            messages.error(request, form.errors)  
            
    
    response = render(request, template_name, context={}) 
    response['X-Robots-Tag'] = 'noindex, nofollow'
    return response 
    
@login_required
def get_reply_form(request, id):
    
    template_name = 'contact/thread_reply_form.html'
    form = ThreadReplyForm()
    thread = ContactMessage.objects.get(id = id)
    
    context = {
        'form' : form,
        'thread' : thread
       
    }
    return render(request, template_name, context=context)


 
@login_required
def threads(request, email): 
    if email != base64_encode(request.user.email) or not request.user.is_staff or not request.user.is_superuser:
        raise PermissionDenied
    
    if not has_threads(request.user.email):
        raise Http404
    
    template_name = 'contact/threads.html'
     
    site = site_info()
    site['title'] = 'Threads'
    site['description'] = 'All Threads of the login user if exists.'
    if request.user.is_staff or request.user.is_superuser:
        threads = ContactMessage.objects.all().order_by('-created_at').prefetch_related('threads')
    else:        
        threads = ContactMessage.objects.filter(email = base64_decode(email)).order_by('-created_at').prefetch_related('threads')
        
        
    page = request.GET.get('page', 1)
    paginator = Paginator(threads, 10)
    try:
        threads = paginator.page(page)
    except PageNotAnInteger:
        threads = paginator.page(1)
    except EmptyPage:
        threads = paginator.page(paginator.num_pages)   
    
    
    context = {
        # 'form' : form,
        'site_data' : site,
        'threads' : threads
    }
    response = render(request, template_name, context=context)
    response['X-Robots-Tag'] = 'noindex, nofollow'
    return response 


# Create your views here.
def contact(request):
    
    template_name = 'contact/contact.html' 
    form = ContactUsForm()
    site_data = site_info()
        
    if request.method == 'POST':
        form = ContactUsForm(request.POST)
        if form.is_valid():
            form.save()            
            messages.success(request, 'Currently we are not taking email. Please sent your query to contact@selfurl.xyz')
            return redirect(reverse_lazy('contact:contact'))
        
            # email_messages = []
            
            # from_email = settings.DEFAULT_FROM_EMAIL               
            
            # # Send email to the site admin
            # admin_subject = f'{site_data["name"]} - New contact form submission'
            # admin_message = f"Name: {form.cleaned_data['name']}\nEmail: {form.cleaned_data['email']}\n\nMessage: {form.cleaned_data['message']}"        
            # admin_reply_to = [form.cleaned_data['email']]        
            # admin_mail = [site_data.get('email')]
            
            
            # email_messages.append((admin_subject, admin_message, from_email, admin_mail , '',  admin_reply_to, ''))
            
            # visitor_subjct = f'{site_data["name"]} - Greetings from {site_data["name"]}!' 
            # visitor_message = f"Dear {form.cleaned_data['name']},\n\nThank you for reaching out to us through our website." 
            # visitor_message += f"We appreciate your interest in {site_data.get('name')}!\n\n"
            # visitor_message += f"This email is to acknowledge that we have received your contact form submission. Please note that this is a no-reply email, "
            # visitor_message += f"so there's no need to reply to it.\n\nA thread have been created at {request.build_absolute_uri(reverse('contact:threads', args=[base64_encode(request.user.email)]))}"
            # visitor_message += f" . You may follow responses there.\n\nOur team is currently reviewing your message, and we will get back to you soon with a response at the designated thread. "
            
            # visitor_message += f"We strive to provide excellent service and address your inquiry promptly.\n\nOnce again, we thank you for getting in touch with us. "
            # visitor_message += f"We look forward to connecting with you!\n\nBest regards,\nThe {site_data.get('name')} Team"
            # visitor_mail = [form.cleaned_data['email']]
            
            # email_messages.append((visitor_subjct, visitor_message, from_email, visitor_mail, '', '', ''))        

            # custom_send_mass_mail(email_messages, fail_silently=False)
            
            
        else:   
            messages.error(request, 'There was an error with your submission. Please try again.')
            
    
       
        
    site = site_info()
    site['title'] = 'Connecting with Us, Simplifying Your URLs'
    site['description'] = f'Contact {site.get("name")} for any inquiries, feedback, or collaboration opportunities. Our dedicated team is here to assist you. Reach out to us through the provided contact details or fill out the contact form on our page. We look forward to hearing from you and providing the support you need.'
    
    
    context = {
        'form' : form,
        'site_data' : site
    }
    response = render(request, template_name, context=context)
    response['X-Robots-Tag'] = 'noindex, nofollow'
    return response 

templates/contact/contact.html
{% extends "layouts/base.html" %}
{% load static %}

{% block robot %}<meta name="robots" content="index">{% endblock %}

{% block content %}


<div class="px-4 py-5 mb-5 text-center  border-bottom ">

    {% if messages %}  
    <div class="col-12 text-center">
        <div class="alert alert-secondary shadow-soft" role="alert">                            
            {% for message in messages %}
            <span class="alert-inner--text">{{ message }}</span>
            {% endfor %}                            
        </div>                        
    </div>
    {# {% include "layouts/ads_display.html" %} #}
    {% endif %}


    <img class="d-block mx-auto mb-4" src="{{ site_data.favicon }}" alt="{{site_data.name}}" width="72" height="72">
    <h1 class="display-5 fw-bold text-primary">{{site_data.title|safe}}</h1>
    <div class="col-lg-12 mx-auto">
        <p class="lead mb-4">{{site_data.description|safe}}.</p>        
    </div>
    <div class="mt-2">
        {# {% include "layouts/ads_boom_your_identity.html" %} #}
    </div>
</div>


<div class="border-bottom mb-5">
    <h2 class="pb-2 border-bottom border-3 border-primary text-danger">Contact us via the form below.</h2>
    {# {% include "layouts/ads_display.html" %} #}
    <div class="row g-4 py-3 row-cols-1">
        <div class="col-12">
            <form method="POST">
                {% csrf_token %}
                <div class="row g-3">
                    <div class="form-group">                   
                        {{ form.name.errors }}
                        {{ form.name }}
                    </div>
                    <div class="input-group">
                        {{ form.phone_number.errors }}
                        {{ form.phone_number }}
                    </div>
                
                    <div class="form-group">
                        {{ form.email.errors }}
                        {{ form.email }}
                    </div>

                    <div class="form-group">
                        {{ form.subject.errors }}
                        {{ form.subject }}
                    </div>

                    <div class="form-group">
                        {{ form.message.errors }}
                        {{ form.message }}
                    </div>

                    <div class="col-12">
                        <div class="form-floating">
                            {{ form.captcha }}
                            
                        </div>
                        <span class="text-error invalid-feedback">{{ form.captcha.errors }}</span>
                    </div>
                

                    <div class="col-12">
                        <button class="btn btn-primary w-100 py-3" type="submit">Send Message</button>
                    </div>
                </div>
            </form>

            {# {% include "layouts/ads_display.html" %} #}
        </div>

        <div class="col-lg-12 mt_md--30 mt_sm--30">
            <div class="google-map-style-1">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2484.0901460398904!2d-0.12378802310095487!3d51.49321321173929!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x487604ea6e333fdd%3A0xcc160edcc16914b6!2s71-75%20Shelton%20Street%2C%20London%20WC2H%209JQ%2C%20UK!5e0!3m2!1sen!2sbd!4v1719115251841!5m2!1sen!2sbd" width="100%" height="550" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
            </div>
        </div>
    </div>
</div>




    {% endblock %}

templates/contact/post_reply.html
<small class="border-bottom">Just Now / {{request.user.email}}</small>
<div>{{reply}}</div>
{% if messages %}  
<div class="col-12 text-center">
    <div class="alert alert-secondary shadow-soft" role="alert">                            
        {% for message in messages %}
        <span class="alert-inner--text">{{ message }}</span>
        {% endfor %}                            
    </div>                        
</div>
{# {% include "layouts/ads_display.html" %} #}
{% endif %}

templates/contact/thread_reply_form.html
{% if messages %}  
<div class="col-12 text-center">
    <div class="alert alert-secondary shadow-soft" role="alert">                            
        {% for message in messages %}
        <span class="alert-inner--text">{{ message }}</span>
        {% endfor %}                            
    </div>                        
</div>
{# {% include "layouts/ads_display.html" %} #}
{% endif %}
<div class="col-12">
    <form class="text-end mt-2 mb-1" hx-post="{% url 'contact:post_reply' thread.id %}" hx-target="#justreply{{thread.id}}" hx-swap="innerHTML">
        {% csrf_token %}
        {{form.as_p}}       
        <button class="badge btn-danger" type="submit">Submit Reply</button>
        {% if request.user.is_superuser or request.user.is_staff %}
        <button class="badge btn-danger" type="submit" hx-target="#justreply{{thread.id}}" hx-trigger="click" hx-vals='{"status": "close"}' hx-post = "{% url 'contact:post_reply' thread.id %}" hx-swap="innerHTML">Reply and Close</button>
        {% endif %}
    </form>
    {# {% include "layouts/ads_display.html" %} #}
</div>

templates/contact/threads.html
{% extends "layouts/base.html" %}
{% load static %}
{% block robot %}<meta name="robots" content="noindex">{% endblock %}
 

{% block content %}


<div class="px-4 py-5 mb-5 text-center  border-bottom ">

    {% if messages %}  
    <div class="col-12 text-center">
        <div class="alert alert-secondary shadow-soft" role="alert">                            
            {% for message in messages %}
            <span class="alert-inner--text">{{ message }}</span>
            {% endfor %}                            
        </div>                        
    </div>
    {# {% include "layouts/ads_display.html" %} #}
    {% endif %}


    <img class="d-block mx-auto mb-4" src="{{ site_data.favicon }}" alt="{{site_data.name}}" width="72" height="72">
    <h1 class="display-5 fw-bold text-primary">{{site_data.title|safe}}</h1>
    <div class="col-lg-12 mx-auto">
        <p class="lead mb-4">{{site_data.description|safe}}.</p>        
    </div>
    <div class="mt-2">
        {# {% include "layouts/ads_boom_your_identity.html" %} #}
    </div>
</div>


<div class="border-bottom mb-5">
    <h2 class="pb-2 border-bottom border-3 border-primary text-danger">All Threads</h2>
    {# {% include "layouts/ads_display.html" %} #}
    <div class="row g-4 py-3 row-cols-1">
        <div class="col-12">
            <div class="accordion" id="accordionExample">
            {% for thread in threads %}
                <div class="accordion-item">
                    <h2 class="accordion-header" id="heading{{thread.id}}">
                    <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{thread.id}}" aria-expanded="true" aria-controls="collapse{{thread.id}}">
                        {{thread.subject}} / {{thread.email}} ({{thread.status}})
                    </button>
                    </h2>
                    <div id="collapse{{thread.id}}" class="accordion-collapse collapse {% if forloop.last %}show {% endif %}" aria-labelledby="heading{{thread.id}}" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                        <div class="mb-4">
                            {{thread.message}}
                        </div>
                        <h5>Replies</h5>
                        <hr>
                        <div class="ms-4">                            
                            {% for reply in thread.threads.all %}
                                <div class="alert alert-dark">
                                    <small class="border-bottom">{{reply.created_at}}/{{reply.reply_email}}</small>
                                    <div>{{reply.message}}</div>
                                </div>
                            {% endfor %}
                         
                            <div id="justreply{{thread.id}}" class="alert alert-info">                       
                            </div>
                            
                        </div>
                        {% if thread.status == 'active' %}
                        <div id="threadform{{thread.id}}" class="d-flex justify-content-end align-items-end mt-2 mb-1">                            
                            <button class="badge btn-danger" type="submit" hx-target="#threadform{{thread.id}}" hx-get="{% url 'contact:get_reply_form' thread.id %}" hx-swap="innerHTML">Reply</button>
                            
                        </div>
                        {% endif %}
                    </div>
                    </div>
                </div>
            {% endfor %}
            </div>
           

            {# {% include "layouts/ads_display.html" %} #}
        </div>

        {% include 'includes/pagination.html' with page=threads %}

        
    </div>
</div>




    {% endblock %}