cms/urls.py
from django.urls import path
from .views import *



app_name = 'cms'

urlpatterns = [   
    path('latest/blogs/', latest_blogs, name='latest_blogs'),       
    path('category/<str:slug>', category_detail, name='category_detail'),    
    path('archive/<int:year>/<int:month>', archive_detail, name='archive_detail'), 
    path('<str:username>/blogs/', user_blogs, name='user_blogs'), 
  
    
]

cms/forms.py
from django import forms

class BlogSearchForm(forms.Form):
    search_query = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder':"Search ...", 'class':'form-control'}))
    

cms/views.py
from django.conf import settings
from django.shortcuts import render
from django.contrib import messages
from main.context_processor import site_info
from django.utils.html import strip_tags
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from main.agent_helper import get_ip
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import random
from django.views.generic.edit import CreateView
from django.db.models import Count, Q
from main.helper import (
    custom_send_mail, 
    custom_send_mass_mail, 
    get_blogs, 
    get_category_with_count,
    get_top_views,
    get_blog_archive
    )
from .models import *
from .forms import *
import calendar
from django.views.decorators.cache import cache_control

import logging
log =  logging.getLogger('log')


# Create your views here.


def get_3_parameter():
    categories = get_category_with_count()   
    
    top_views = get_top_views()    
    
    blog_archive =  get_blog_archive()
    
    return categories, top_views, blog_archive
    
    
def archive_detail(request, year, month):
    template_name = 'cms/category_details.html'  
    
    search_form = BlogSearchForm()
    if 'search_query' in request.GET:
        search_form = BlogSearchForm(request.GET)        
        if search_form.is_valid():
            search_query = search_form.cleaned_data['search_query']    
            blogs = Blog.published.filter(
                (Q(title__icontains=search_query) | Q(body__icontains=search_query)), updated_at__year=year, updated_at__month=month
            )          
    else:   
        blogs = Blog.published.filter(updated_at__year=year, updated_at__month=month)
    
         

    categories, top_views, blog_archive = get_3_parameter()

    paginator = Paginator(blogs, 10) 

    page_number = request.GET.get('page')
    
    try:
        blogs = paginator.page(page_number)
    except PageNotAnInteger:
        blogs = paginator.page(1)
    except EmptyPage:
        blogs = paginator.page(paginator.num_pages) 
        
        
    site = site_info()
    site['title'] = f'Blog archive of {calendar.month_name[month]}, {year}'
    site['description'] = f'Discover a wealth of valuable insights, tips, and knowledge in our blog archive. Explore a wide range of topics, from tech trends to marketing strategies. Stay informed and inspired with our collection of informative blog posts.'
    
     
    context = {
        'search_form': search_form,
        'blogs': blogs,
        'site_data' : site,
        'categories' : categories,
        'top_views' : top_views,
        'blog_archive' : blog_archive,

    }
    
    response = render(request, template_name, context=context)
    response['X-Robots-Tag'] = 'index, follow'
    return response 


@cache_control(no_cache=True, must_revalidate=True, no_store=True)   
def category_detail(request, slug):
    
    template_name = 'cms/category_details.html'  

    category = get_object_or_404(Category.objects.prefetch_related('blogs_category'), slug=slug)   
    search_form = BlogSearchForm()
    
    if 'search_query' in request.GET:
        search_form = BlogSearchForm(request.GET)        
        if search_form.is_valid():
            search_query = search_form.cleaned_data['search_query']    
            blogs = category.blogs_category.filter(
                (Q(title__icontains=search_query) | Q(body__icontains=search_query)),
                status = 'published'
            )          
    else:        
        blogs = category.blogs_category.filter(status = 'published')       
 
    
    categories, top_views, blog_archive = get_3_parameter()     
    

    paginator = Paginator(blogs, 10) 

    page_number = request.GET.get('page')
    
    try:
        blogs = paginator.page(page_number)
    except PageNotAnInteger:
        blogs = paginator.page(1)
    except EmptyPage:
        blogs = paginator.page(paginator.num_pages) 
        
        
    site = site_info()
    site['title'] = f'Unlocking Knowledge, Category by {category.title}'  
    site['description'] = category.description
    
     
    context = {
        'search_form': search_form,
        'category' : category,
        'blogs': blogs,
        'site_data' : site,
        'categories' : categories,
        'top_views' : top_views,
        'blog_archive' : blog_archive
    }
    
    response = render(request, template_name, context=context)
    response['X-Robots-Tag'] = 'index, follow'
    return response 

def user_blogs(request, username):
    
    template_name = 'cms/category_details.html'  
    
    search_form = BlogSearchForm()
    
    if 'search_query' in request.GET:
        search_form = BlogSearchForm(request.GET)        
        if search_form.is_valid():
            search_query = search_form.cleaned_data['search_query']    
            blogs = Blog.published.filter(
                (Q(title__icontains=search_query) | Q(body__icontains=search_query)), 
                creator__username = username
            )          
    else:
        blogs = Blog.published.filter(creator__username = username) 
 
    
    categories, top_views, blog_archive = get_3_parameter()     
    

    paginator = Paginator(blogs, 10) 

    page_number = request.GET.get('page')
    
    try:
        blogs = paginator.page(page_number)
    except PageNotAnInteger:
        blogs = paginator.page(1)
    except EmptyPage:
        blogs = paginator.page(paginator.num_pages) 
        
        
    site = site_info()
    site['title'] = f'Latest Blogs of Creator: {username}'    
    site['description'] = f"Welcome to {username}'s blog, where you'll find a wealth of valuable insights and personal experiences. Explore a diverse range of topics, including {username}'s areas of expertise or interests, and gain unique perspectives on relevant industry or subject. Expand your knowledge and engage with thought-provoking content on {username}'s blog."
    
     
    context = {
        'search_form': search_form,
        'blogs': blogs,
        'site_data' : site,
        'categories' : categories,
        'top_views' : top_views,
        'blog_archive' : blog_archive
    }
    
    response = render(request, template_name, context=context)
    response['X-Robots-Tag'] = 'index, follow'
    return response 


def latest_blogs(request):
    
    template_name = 'cms/category_details.html'
    
    search_form = BlogSearchForm()
    
    if 'search_query' in request.GET:
        search_form = BlogSearchForm(request.GET)        
        if search_form.is_valid():
            search_query = search_form.cleaned_data['search_query']
            blogs = Blog.published.filter(
                Q(title__icontains=search_query) | Q(body__icontains=search_query)
            )             
    else:
        blogs = get_blogs()
    
    categories, top_views, blog_archive = get_3_parameter()     
    

    paginator = Paginator(blogs, 10) 

    page_number = request.GET.get('page')
    
    try:
        blogs = paginator.page(page_number)
    except PageNotAnInteger:
        blogs = paginator.page(1)
    except EmptyPage:
        blogs = paginator.page(paginator.num_pages) 
        
        
    site = site_info()
    site['title'] = f'Stay Updated with Our Latest Insights and Expert Blog Posts' 
    site['description'] = 'Explore our latest blog posts for valuable insights, expert tips, and industry trends. Stay informed with our informative and engaging content on various topics. Read now!'
    
     
    context = {
        'search_form': search_form,
        'blogs': blogs,
        'site_data' : site,
        'categories' : categories,
        'top_views' : top_views,
        'blog_archive' : blog_archive
    }
    
    response = render(request, template_name, context=context)
    response['X-Robots-Tag'] = 'index, follow'
    return response 

def page_detail(request, slug):
    template_name = 'cms/page_detail.html'
    
    page = get_object_or_404(Page, slug=slug) 

    page.view(request)     
    
    site = site_info()
     
     
    #render {} wraped syntax from site dictionary
    rendered_body = page.body.format(**site)
    page.body = rendered_body
    
    banner = page.top_banenr.url if page.top_banenr else site.get('og_image')
    
    site['title'] = page.top_tagline
    site['description'] = page.meta_description
    site['og_image'] = banner
    
    
    
    
    context = {
        'page' : page,
        'site_data' : site
    }
    
    response = render(request, template_name, context=context)   
    response['X-Robots-Tag'] = 'index, follow'
    return response 


@cache_control(no_cache=True, must_revalidate=True, no_store=True)   
def blog_detail(request, slug):
    template_name = 'cms/blog_detail.html'
    
    blog = get_object_or_404(Blog.published.prefetch_related('categories'), slug=slug)   
     
    blog.view(request)    
 
        
    site = site_info()
    site['title'] = blog.title[:45]
    truncated_string = strip_tags(blog.body)[:160]
    site['description'] = truncated_string
    site['og_image'] = blog.feature.url
    
    
    context = {      
        'blog' : blog,   
        'site_data' : site,      
    }   
    
    response = render(request, template_name, context=context)
    response['X-Robots-Tag'] = 'index, follow'
    return response 

    



    

templates/cms/blog_detail.html
{% extends "layouts/base.html" %}
{% load static %}

{% block robot %}<meta name="robots" content="index">{% endblock %}
{% block content %}

<div class="px-4 py-5 mb-5 text-center  border-bottom ">
    <img class="d-block mx-auto mb-4" src="{{ site_data.favicon }}" alt="{{site_data.name}}" width="72" height="72">
    <h1 class="display-5 fw-bold text-primary">{{site_data.title|safe}}</h1>
    <div class="mt-2">
        {# {% include "layouts/ads_boom_your_identity.html" %} #}
    </div>
    <ul class="list-inline">
        <li class="list-inline-item">       
            <a href="{% url 'cms:user_blogs' blog.creator.username %}">{{blog.creator.username}}</a>
        </li>   
        /
        <li class="list-inline-item">    
            {{blog.updated_at|date:"F j, Y" }}
        </li>        
    </ul>
</div>

<div class="col-lg-12 mb-3">
             
        <a href="{{blog.get_absolute_url}}">
            <img class="img-fluid w-100" src="{{blog.feature.url}}" alt="{{blog.title}}" title="{{blog.title}}">
        </a>                        
        <div class="border-bottom border-2 px-5 pt-5 text-justify">            
            {{ blog.body|safe}}
        </div>

        <div class="border-bottom border-2 px-5 py-2 text-justify">Views: {{blog.total_view }}</div>
        <div class="border-bottom border-2 px-5 py-2 text-justify">   
            <div class="tag-cloud">
                {% for cat in blog.categories.all %}
                <a class="badge bg-primary" href="{{ cat.get_absolute_url }}">{{cat.title}}</a>
                {% endfor %}                
            </div>
        </div>


        
    
</div>






{% endblock %}

{% block javascripts %}



{% endblock javascripts %}

templates/cms/category_details.html
{% extends "layouts/base.html" %}
{% load static %}


{% block robot %}<meta name="robots" content="index">{% endblock %}

{% block content %}

<div class="px-4 py-5 mb-5 text-center  border-bottom ">
    <img class="d-block mx-auto mb-4" src="{{ site_data.favicon }}" alt="{{site_data.name}}" width="72" height="72">
    <h1 class="display-5 fw-bold text-primary">{{site_data.title|safe}}</h1>   
</div>


<div class="container mb-5">
    <div class="row">
        <div class="col-lg-8">
            <div class="row">
                {% for blog in blogs %}
                    <div class="col-lg-12 mb-3">
                        <div class="card flex-fill">             
                            <a href="{{blog.get_absolute_url}}">
                                <img class="img-fluid" src="{{blog.feature.url}}" alt="{{blog.title}}" title="{{blog.title}}">
                            </a>                        
                            <div class="card-body">
                                <h4 class="card-title">
                                    <a href="{{blog.get_absolute_url}}">{{blog.title}}</a>
                                </h4>
                                <ul class="list-inline">
                                    <li class="list-inline-item"><a href="{% url 'cms:user_blogs' blog.creator.username %}">{{ blog.creator.username }}</a></li>
                                    <li class="separator list-inline-item">/</li>
                                    <li class="list-inline-item">{{blog.updated_at|date:"F j, Y" }}</li>
                                </ul>
                                {{ blog.body|safe|truncatechars:250 }}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            {% include 'includes/pagination.html' with page=blogs %} 
        </div>
        <div class="col-lg-4">
            <div class="row">
                <div class="col-lg-12">
                    <form class="blog-search" method="GET">
                        <div class="input-group mb-3">
                            {{ search_form.search_query }}                                            
                            <button type="submit" class="btn btn-sm btn-primary">
                                FIND
                            </button>
                        </div>
                    </form>
                </div>

                <div class="col-lg-12">
                    <h3 class="custom-underline lead fw-bold">Categories</h3>
            
                        <ul class="list-group list-group-flush">
                            {% for cat in categories %}                            
                            <li class="list-group-item">
                                <a class="{% if cat.get_absolute_url == request.path %} active {% endif %} link-danger" href="{{cat.get_absolute_url}}">
                                    <span class="left-content">{{cat.title}}</span>
                                    <span class="count-text">{{ cat.blog_count }}</span>
                                </a>
                            </li>
                            {% endfor %}
                            
                        </ul>
               
                </div>
                <div class="col-lg-12">
                    <h3 class="custom-underline-green lead fw-bold">Top Views</h3>
                    
                        <ul class="list-group list-group-flush">
                            {% for b in top_views %}
                                <li class="list-group-item"><a class="link-success {% if b.get_absolute_url == request.path %} active {% endif %}" href="{{b.get_absolute_url}}">{{b.title}}({{b.total_view_count}})</a></li>
                            {% endfor %}                            
                        </ul>
                    
                </div>
                <div class="col-lg-12">
                    <h3 class="custom-underline-blue lead fw-bold">Archives</h3>                       
                        <ul class="list-group list-group-flush">                              
                            {% for ba in blog_archive %}
                                {% url 'cms:archive_detail' year=ba.month|date:'Y' month=ba.month|date:'m' as archive_url %}                                          
                                <li class="list-group-item">
                                    <a href="{{ archive_url }}" class="cate {% if archive_url == request.path %}active{% endif %}">
                                        {{ ba.month|date:"F Y" }}
                                    </a>
                                </li>
                            {% endfor %}
                            
                        </ul>
                    
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

templates/cms/page_detail.html
{% extends "layouts/base.html" %}
{% load static %}

{% block robot %}<meta name="robots" content="index">{% endblock %}

{% block content %}
<div class="px-4 py-5 mb-5 text-center  border-bottom ">
    <img class="d-block mx-auto mb-4" src="{{ site_data.favicon }}" alt="{{site_data.title}}" width="72" height="72">
    <h1 class="display-5 fw-bold text-primary">{{site_data.title}}</h1>
    <div class="mt-2">
        
    </div>
    
</div>

{{ page.body|safe }}


{% endblock %}